### PR TITLE
WIP: Support for @SUMMONVARNAMES

### LINKED ISSUE #199: Make list of environment variable names available in child process
## Is your feature request related to a problem? Please describe

If we strip both `@SUMMONENVFILE` and the proposed  [`@SUMMONDOCKERARGS`](#9)we see that at the core they use the list of summon injected envvar names. If you know that the envvars that summon injected are A, B and C, then the rest can be done in bash or otherwise with relative ease.

This allows us to not build special cases into Summon. Instead wee provide a primitive to accommodate such cases and beyond.

## Describe the solution you would like

Perhaps Summon injects a special environment variable called `SUMMONVARNAMES` or has a substitution variable like  `@SUMMONENVFILE` called `@SUMMONVARNAMES`.

## Describe alternatives you have considered

N/A

## Additional context

N/A

### PR DESCRIPTION
**Pull request by doodlesbykumbi**
### What does this PR do?

`@SUMMONVARNAMES` makes this possible, which avoids the multiline issues of `@SUMMONENVFILE`.
```
$ summon -p keyring.py -D env=dev env SUMMONVARNAMES=@SUMMONVARNAMES sh << EOL
docker run \$(printenv SUMMONVARNAMES | xargs printf -- '--env %s ' | xargs) deployer
EOL
```

- _What's changed? Why were these changes made?_
- _How should the reviewer approach this PR, especially if manual tests are required?_
- _Are there relevant screenshots you can add to the PR description?_

### What ticket does this PR close?
Resolves #199 

#### Change log
- [ ] The CHANGELOG has been updated, or
- [ ] This PR does not include user-facing changes and doesn't require a CHANGELOG update

#### Test coverage
- [ ] This PR includes new unit and integration tests to go with the code changes, or
- [ ] The changes in this PR do not require tests

#### Documentation
- [ ] Docs (e.g. `README`s) were updated in this PR, and/or there is a follow-on issue to update docs, or
- [ ] This PR does not require updating any documentation

### CODE REVIEW

**Comment by ryanneufeld** [comment]
This would be fantastic to have

**Comment by ryanneufeld** [comment]
@jtuttle Any way this could be added?

**Comment by jtuttle** [comment]
@doodlesbykumbi Is this ready for review? I see it still says WIP.

**Comment by doodlesbykumbi** [comment]
@jtuttle This PR was and to some extent still is really just experimental. We never got to a point where we found an approach that we were entirely happy with.

**Pull request closed without merging**
