### PR TITLE
Update dependencies for cucumber and aruba

### PR DESCRIPTION
**Pull request by juniortaeza**
### Desired Outcome

Resolves Cucumber's medium severity in Snyk for potential HTML injection in versions before 4.0

### Implemented Changes

Updates acceptance/Gemfile.lock entirely to include most up-to-date versions of gems and dependencies

### Connected Issue/Story

CyberArk internal issue link: [CONJSE-1519](https://ca-il-jira.il.cyber-ark.com:8443/browse/CONJSE-1519)

### Definition of Done
*At least 1 todo must be completed in the sections below for the PR to be
merged.*

#### Changelog

- [x] The CHANGELOG has been updated, or
- [ ] This PR does not include user-facing changes and doesn't require a
  CHANGELOG update

#### Test coverage

- [ ] This PR includes new unit and integration tests to go with the code
  changes, or
- [x] The changes in this PR do not require tests

#### Documentation

- [ ] Docs (e.g. `README`s) were updated in this PR
- [ ] A follow-up issue to update official docs has been filed here: [insert issue ID]()
- [x] This PR does not require updating any documentation

#### Behavior

- [ ] This PR changes product behavior and has been reviewed by a PO, or
- [x] These changes are part of a larger initiative that will be reviewed later, or
- [ ] No behavior was changed with this PR

#### Security

- [ ] Security architect has reviewed the changes in this PR,
- [x] These changes are part of a larger initiative with a separate security review, or
- [ ] There are no security aspects to these changes

### CODE REVIEW

**Comment by rpothier** [comment]
@adamouamani should we update to Cucumber 7?

**Comment by juniortaeza** [comment]
> > @adamouamani should we update to Cucumber 7?
> 
> Thanks @rpothier Would be good to harmonize on version 7.1.0 of Cucumber which we use on other repo's

hi Adam! in case there are dependencies that 7.1.0 requires that I am unable to write to the gemfile, what are the possibilities of updating the entire docker image we are pulling from with the newest bundle + dependency updates?

**Comment by juniortaeza** [comment]
@adamouamani @rpothier 

updating to Cucumber 7.1.0 deeply requires other dependencies to be updated. I've updated as much as I can with gherkin, messages, etc. but can't seem to get past this point:

Downloading cucumber-core-7.0.0 revealed dependencies not in the API or the
#12 55.93 lockfile (cucumber-gherkin (>= 13.0.0, ~> 13.0), cucumber-messages (>= 12.1.1,
#12 55.93 ~> 12.1), cucumber-tag-expressions (>= 2.0.4, ~> 2.0)).
#12 55.93 Either installing with `--full-index` or running `bundle update cucumber-core`
#12 55.93 should fix the problem.

**Review by rpothier — CHANGES_REQUESTED** [review]
Looks good! A minor comments, please add a new line at the end of Genfile.lock and squash the commits.

**Comment by juniortaeza** [comment]
> Looks good! A minor comments, please add a new line at the end of Genfile.lock and squash the commits.

sounds good! I'll also update the CHANGELOG as well. thank you!

**Comment by rpothier** [comment]
Looks good, the changelog still says cucumber 4.x

**Comment by juniortaeza** [comment]
> Looks good, the changelog still says cucumber 4.x

ah, looks like I might've accidentally hit undo and saved. Fixed!

**Review by rpothier — APPROVED** [review]
LGTM!

**Pull request merged**
